version: '3.3'
services:

  database:
    container_name: development_portfolio_database
    image: mongo:3.6
    restart: always
    volumes:
      - ./database:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD}
      MONGO_INITDB_DATABASE: ${DB_NAME}
    ports:
     - 27017:27017

  database_manager:
    container_name: development_portfolio_database_manager
    image: mongo-express:1.0.0-alpha
    restart: always
    environment:
      ME_CONFIG_MONGODB_SERVER: ${DB_URL}
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${DB_USER}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${DB_PASSWORD}
      ME_CONFIG_BASICAUTH_USERNAME: ${DB_USER}
      ME_CONFIG_BASICAUTH_PASSWORD: ${DB_PASSWORD}
    ports:
      - 8080:8081

  backend:
    container_name: development_portfolio_backend
    restart: on-failure:15
    build:
      context: backend/.
    environment:
      DB_URL: ${DB_URL}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      API_PORT: ${API_PORT}
    depends_on:
     - database
    links:
     - database
    ports:
     - 4000:4000