export { default as Bold } from './Bold/Bold'
export { default as Image } from './Image/Image'
export { default as H1 } from './H1/H1'
export { default as H2 } from './H2/H2'
export { default as H5 } from './H5/H5'
export { default as H6 } from './H6/H6'
export { default as Small } from './Small/Small'