// Package docs GENERATED BY SWAG; DO NOT EDIT
// This file was generated by swaggo/swag
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "Jesús \"VoN\" Rodríguez",
            "url": "https://mx.linkedin.com/in/jes%C3%BAs-%C3%A1ngel-rodr%C3%ADguez-mart%C3%ADnez-84991a1b4",
            "email": "sudo.von.contact@gmail.com"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/blogs": {
            "get": {
                "security": [
                    {
                        "BearerJWT": []
                    }
                ],
                "description": "List blogs.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "blogs"
                ],
                "summary": "List blogs.",
                "operationId": "list-blogs",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handler.BlogResponseList"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "handler.BlogResponse": {
            "type": "object",
            "properties": {
                "category": {
                    "type": "string",
                    "example": "hacking"
                },
                "creation_date": {
                    "type": "string",
                    "example": "2021-10-10"
                },
                "description": {
                    "type": "string",
                    "example": "How to perform a SQLInjection attack"
                },
                "id": {
                    "type": "string",
                    "example": "613aab578a6ef50007e622be"
                },
                "main_picture_url": {
                    "type": "string",
                    "example": "https://www.fake-main-picture-url.com/sqlinjection"
                },
                "title": {
                    "type": "string",
                    "example": "SQLInjection"
                },
                "views": {
                    "type": "integer",
                    "example": 1000
                }
            }
        },
        "handler.BlogResponseList": {
            "type": "object",
            "properties": {
                "result": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/handler.BlogResponse"
                    }
                },
                "total": {
                    "type": "integer",
                    "example": 1
                }
            }
        }
    },
    "securityDefinitions": {
        "BasicAuth": {
            "type": "basic"
        },
        "BearerJWT": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0.0",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "sudo-von API",
	Description:      "Official documentation to consume the API. You can find out more about this API at https://github.com/sudo-von/frontend.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
