basePath: /api/v1
info:
  contact:
    email: sudo.von.contact@gmail.com
    name: Jesús "VoN" Rodríguez
    url: https://mx.linkedin.com/in/jes%C3%BAs-%C3%A1ngel-rodr%C3%ADguez-mart%C3%ADnez-84991a1b4
  description: Official documentation to consume the API. You can find out more about
    this API at https://github.com/sudo-von/frontend.
  termsOfService: http://swagger.io/terms/
  title: Sudo-von API
  version: 1.0.0
paths: {}
securityDefinitions:
  BasicAuth:
    type: basic
  BearerJWT:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
